### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by sebastianmacias** [buffcode/ntp-time-sync#1]
Hi, 

I'm getting the following error:

```bash
This dependency was not found:

* dgram in ./node_modules/ntp-time-sync/dist/index.js

To install it, you can run: npm install --save dgram


```

Same error after installing [dgram](https://www.npmjs.com/package/dgram). Looks like it's related to the fact that dgram is not longer a project on npm.

Thanks

**Comment by buffcode** [comment]
`dgram` is part of the NodeJS core: https://nodejs.org/api/dgram.html
Which version of node are you using?

**Comment by sebastianmacias** [comment]
I'm using 8.9.4
```
dev@DevX:[~]: node -v
v8.9.4
dev@DevX:[~]: npm -v
5.6.0
dev@DevX:[~]: yarn -v
1.3.2


```

**Comment by sebastianmacias** [comment]
Do I need to use v9.5.0?

**Comment by sebastianmacias** [comment]
Installed v9.5.0, didn't work either. I'm getting the same error.

**Comment by kayakyakr** [comment]
Are you trying to use in a client-side project? If so, UDP is not available from the browser and you are limited to ajax-emulation of an NTP client.

**Comment by samaneh-kamalian** [comment]
> Hi,
> 
> I'm getting the following error:
> 
> ```shell
> This dependency was not found:
> 
> * dgram in ./node_modules/ntp-time-sync/dist/index.js
> 
> To install it, you can run: npm install --save dgram
> ```
> 
> Same error after installing [dgram](https://www.npmjs.com/package/dgram). Looks like it's related to the fact that dgram is not longer a project on npm.
> 
> Thanks

same problem

**Comment by buffcode** [comment]
This package is only useful in a NodeJS context and cannot be used within a browser.
[`dgram`](https://nodejs.org/api/dgram.html#dgram_udp_datagram_sockets) is part of the NodeJS API.

I updated the README to clarify this.
