### ISSUE TITLE
Connection error from past 2 days

### ISSUE THREAD

**Issue by chandrakanthi07** [buffcode/ntp-time-sync#2]
I am getting the below error from past 2 days. This module was giving correct result one month back.
Error: Connection error: Unable to get any NTP response after 3 retries
    at NtpTimeSync.collectSamples (vendor.bundle.js:119319)

**Comment by buffcode** [comment]
Did you check for connection issues?
Maybe the NTP servers are not reachable or the UDP packets cannot be routed back to your service?

This error will be thrown when no responses were received / all requests threw errors.

See https://github.com/buffcode/ntp-time-sync/blob/master/src/index.js#L113.

**Comment by chandrakanthi07** [comment]
I pinged the pool server and it was successful.

**Comment by num-lock** [comment]
@chandrakanthi07 Ping uses ICMP and not UDP, which is used by NTP. Successfully pinging a server does not rule out errors with your UDP routing.

**Comment by banagale** [comment]
I also am getting this error. Here's a sandbox of an implementation I'm using locally showing the errors.  I tried passing in alternate time servers and had the same issue.

https://codesandbox.io/s/ntp-time-sync-6nl0m?file=/src/App.js

**Comment by redstubble** [comment]
@banagale This library will not work client side as it requires a UDP connection (not possible with browsers). This error should be handled better to check if dgram is available.

**Comment by buffcode** [comment]
@chandrakanthi07 @banagale The NTP protocol defines when data has to be discarded.
You can see the possible reasons [here](https://github.com/buffcode/ntp-time-sync/blob/f632a7dc47707ab8c500b503919d2d13c40b2857/src/NtpTimeSync.ts#L399) in the code.

Currently there is no way to receive the errors from this library (as error handling is part of the NTP protocol).
For debugging purposes you could add a `console.log(result);` call [here](https://github.com/buffcode/ntp-time-sync/blob/f632a7dc47707ab8c500b503919d2d13c40b2857/src/NtpTimeSync.ts#L165).

As @redstubble said this can only be tested/used with NodeJS. Browsers unfortunately don't support native UDP socket access.

**Comment by buffcode** [comment]
Please reopen if there are any more issues
