### ISSUE TITLE
package is useless .getInstance is not a function

### ISSUE THREAD

**Issue by digimbyte** [buffcode/ntp-time-sync#4]
installed with `npm i ntp-time-sync`
referenced with `import NtpTimeSync from 'ntp-time-sync';`
called at `const timeSync = NtpTimeSync.getInstance();`

Error: index.js:221
const timeSync = NtpTimeSync.getInstance();
                             ^
TypeError: NtpTimeSync.getInstance is not a function

**Comment by leeanson19** [comment]
I have the same issue here.

**Comment by digimbyte** [comment]
Found a solution, Don't use this package, they are only exporting es6 and will be incompatible.

**Comment by buffcode** [comment]
I have updated the package to TypeScript, also there are no default exports anymore.

The new syntax is:
```js
import { NtpTimeSync } from "ntp-time-sync";
```

Please checkout v0.2.0 and the `examples/example.js`.
Thank you!
