### ISSUE TITLE
Add support for NodeJS 20.xx LTS

### ISSUE THREAD

**Issue by paulr113** [buffcode/ntp-time-sync#69]
Hey there,

I ran into an issue trying to install this module with the latest LTS version of NodeJS. Here's the error message I got:

```
error ntp-time-sync@0.3.1: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^18". Got "20.10.0"
```

Any chance we could get support for NodeJS 20?

Thanks a bunch for your work!

**Comment by buffcode** [comment]
Node v20 is supported with 0.4.1
